"""rename department

Revision ID: 361fb9a02b07
Revises: 46b0d1274522
Create Date: 2024-05-19 20:11:01.017720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361fb9a02b07'
down_revision = '46b0d1274522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
